In [30]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', False)

In [31]:
path = '../data/raw/usa characteristics.csv'
data = pd.read_csv(path)
data

,id,date,eom,source_crsp,size_grp,obs_main,exch_main,primary_sec,gvkey,iid,...,rvol_252d,zero_trades_252d,corr_1260d,betabab_1260d,rmax5_rvol_21d,age,qmj,qmj_prof,qmj_growth,qmj_safety
0,10026,20240131,20240131,1,small,1,1,1,12825.0,1.0,...,NaN,NaN,NaN,NaN,NaN,469,1.284129,1.204025,-0.067640,1.448983
1,10026,20240229,20240229,1,small,1,1,1,12825.0,1.0,...,NaN,NaN,NaN,NaN,NaN,470,1.282924,1.198607,-0.075588,1.449240
2,10026,20240328,20240331,1,small,1,1,1,12825.0,1.0,...,NaN,NaN,NaN,NaN,NaN,471,1.280630,1.196231,-0.075454,1.447640
3,10026,20240430,20240430,1,small,1,1,1,12825.0,1.0,...,NaN,NaN,NaN,NaN,NaN,472,1.423064,1.291237,0.204842,1.430103
4,10026,20240531,20240531,1,small,1,1,1,12825.0,1.0,...,NaN,NaN,NaN,NaN,NaN,473,1.426046,1.291984,0.203015,1.429422
5,10026,20240628,20240630,1,small,1,1,1,12825.0,1.0,...,0.019756,0.005127,NaN,NaN,0.663480,474,1.424819,1.285306,0.200853,1.424767
6,10026,20240731,20240731,1,small,1,1,1,12825.0,1.0,...,0.018842,0.005171,NaN,NaN,0.774694,475,1.375874,1.290799,0.165077,1.357295
7,10026,20240830,20240831,1,small,1,1,1,12825.0,1.0,...,0.019098,0.005187,NaN,NaN,1.458593,476,1.359689,1.282651,0.150416,1.352312
8,10026,20240930,20240930,1,small,1,1,1,12825.0,1.0,...,0.018334,0.005257,NaN,NaN,0.690187,477,1.361963,1.281207,0.150217,1.353159
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2332902,135685901,20251231,20251231,0,mega,1,1,1,356859.0,1.0,...,NaN,NaN,NaN,NaN,NaN,36,NaN,NaN,NaN,NaN
2332903,136691101,20250630,20250630,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,42,NaN,NaN,NaN,NaN
2332904,136691101,20250731,20250731,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,43,NaN,NaN,NaN,NaN
2332905,136691101,20250829,20250831,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,44,NaN,NaN,NaN,NaN
2332906,136691101,20250930,20250930,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,45,NaN,NaN,NaN,NaN
2332907,136691101,20251031,20251031,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,46,NaN,NaN,NaN,NaN
2332908,136691101,20251128,20251130,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,47,NaN,NaN,NaN,NaN
2332909,136691101,20251231,20251231,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,48,NaN,NaN,NaN,NaN
2332910,136935001,20251231,20251231,0,mega,1,1,1,369350.0,1.0,...,NaN,NaN,NaN,NaN,NaN,36,NaN,NaN,NaN,NaN

In [32]:
print(data.columns.tolist())

['id', 'date', 'eom', 'source_crsp', 'size_grp', 'obs_main', 'exch_main', 'primary_sec', 'gvkey', 'iid', 'permno', 'permco', 'excntry', 'curcd', 'fx', 'common', 'comp_tpci', 'crsp_shrcd', 'comp_exchg', 'crsp_exchcd', 'adjfct', 'shares', 'me', 'me_lag1', 'gics', 'sic', 'naics', 'ff49', 'me_company', 'prc', 'prc_local', 'dolvol', 'ret', 'ret_local', 'ret_exc', 'ret_lag_dif', 'ret_exc_lead1m', 'market_equity', 'enterprise_value', 'book_equity', 'assets', 'sales', 'net_income', 'bidask', 'prc_high', 'prc_low', 'tvol', 'div1m_me', 'div3m_me', 'div6m_me', 'div12m_me', 'divspc1m_me', 'divspc12m_me', 'chcsho_1m', 'chcsho_3m', 'chcsho_6m', 'chcsho_12m', 'eqnpo_1m', 'eqnpo_3m', 'eqnpo_6m', 'eqnpo_12m', 'ret_1_0', 'ret_2_0', 'ret_3_0', 'ret_3_1', 'ret_6_0', 'ret_6_1', 'ret_9_0', 'ret_9_1', 'ret_12_0', 'ret_12_1', 'ret_12_7', 'ret_18_1', 'ret_24_1', 'ret_24_12', 'ret_36_1', 'ret_36_12', 'ret_48_12', 'ret_48_1', 'ret_60_1', 'ret_60_12', 'ret_60_36', 'seas_1_1an', 'seas_1_1na', 'seas_2_5an', 'seas_2_5na', 'seas_6_10an', 'seas_6_10na', 'seas_11_15an', 'seas_11_15na', 'seas_16_20an', 'seas_16_20na', 'at_gr1', 'ca_gr1', 'nca_gr1', 'lt_gr1', 'cl_gr1', 'ncl_gr1', 'be_gr1', 'pstk_gr1', 'debt_gr1', 'sale_gr1', 'cogs_gr1', 'sga_gr1', 'opex_gr1', 'capx_gr1', 'inv_gr1', 'at_gr3', 'ca_gr3', 'nca_gr3', 'lt_gr3', 'cl_gr3', 'ncl_gr3', 'be_gr3', 'pstk_gr3', 'debt_gr3', 'sale_gr3', 'cogs_gr3', 'sga_gr3', 'opex_gr3', 'capx_gr3', 'cash_gr1a', 'inv_gr1a', 'rec_gr1a', 'ppeg_gr1a', 'lti_gr1a', 'sti_gr1a', 'intan_gr1a', 'debtst_gr1a', 'ap_gr1a', 'txp_gr1a', 'debtlt_gr1a', 'txditc_gr1a', 'coa_gr1a', 'col_gr1a', 'cowc_gr1a', 'ncoa_gr1a', 'ncol_gr1a', 'nncoa_gr1a', 'oa_gr1a', 'ol_gr1a', 'fna_gr1a', 'fnl_gr1a', 'nfna_gr1a', 'gp_gr1a', 'ebitda_gr1a', 'ebit_gr1a', 'ope_gr1a', 'ni_gr1a', 'nix_gr1a', 'dp_gr1a', 'fincf_gr1a', 'ocf_gr1a', 'fcf_gr1a', 'nwc_gr1a', 'eqnetis_gr1a', 'dltnetis_gr1a', 'dstnetis_gr1a', 'dbnetis_gr1a', 'netis_gr1a', 'eqnpo_gr1a', 'tax_gr1a', 'eqbb_gr1a', 'eqis_gr1a', 'div_gr1a', 'eqpo_gr1a', 'capx_gr1a', 'be_gr1a', 'cash_gr3a', 'inv_gr3a', 'rec_gr3a', 'ppeg_gr3a', 'lti_gr3a', 'intan_gr3a', 'debtst_gr3a', 'ap_gr3a', 'txp_gr3a', 'debtlt_gr3a', 'txditc_gr3a', 'coa_gr3a', 'col_gr3a', 'cowc_gr3a', 'ncoa_gr3a', 'ncol_gr3a', 'nncoa_gr3a', 'oa_gr3a', 'ol_gr3a', 'fna_gr3a', 'fnl_gr3a', 'nfna_gr3a', 'gp_gr3a', 'ebitda_gr3a', 'ebit_gr3a', 'ope_gr3a', 'ni_gr3a', 'nix_gr3a', 'dp_gr3a', 'fincf_gr3a', 'ocf_gr3a', 'fcf_gr3a', 'nwc_gr3a', 'eqnetis_gr3a', 'dltnetis_gr3a', 'dstnetis_gr3a', 'dbnetis_gr3a', 'netis_gr3a', 'eqnpo_gr3a', 'tax_gr3a', 'eqbb_gr3a', 'eqis_gr3a', 'div_gr3a', 'eqpo_gr3a', 'capx_gr3a', 'capx_at', 'rd_at', 'spi_at', 'xido_at', 'nri_at', 'gp_sale', 'ebitda_sale', 'ebit_sale', 'pi_sale', 'ni_sale', 'nix_sale', 'ocf_sale', 'fcf_sale', 'gp_at', 'ebitda_at', 'ebit_at', 'fi_at', 'cop_at', 'ni_at', 'ope_be', 'ni_be', 'nix_be', 'ocf_be', 'fcf_be', 'gp_bev', 'ebitda_bev', 'ebit_bev', 'fi_bev', 'cop_bev', 'gp_ppen', 'ebitda_ppen', 'fcf_ppen', 'fincf_at', 'netis_at', 'eqnetis_at', 'eqis_at', 'dbnetis_at', 'dltnetis_at', 'dstnetis_at', 'eqnpo_at', 'eqbb_at', 'div_at', 'oaccruals_at', 'oaccruals_ni', 'taccruals_at', 'taccruals_ni', 'noa_at', 'be_bev', 'debt_bev', 'cash_bev', 'pstk_bev', 'debtlt_bev', 'debtst_bev', 'int_debt', 'int_debtlt', 'ebitda_debt', 'profit_cl', 'ocf_cl', 'ocf_debt', 'cash_lt', 'inv_act', 'rec_act', 'debtst_debt', 'cl_lt', 'debtlt_debt', 'lt_ppen', 'debtlt_be', 'opex_at', 'nwc_at', 'fcf_ocf', 'debt_at', 'debt_be', 'ebit_int', 'inv_days', 'rec_days', 'ap_days', 'cash_conversion', 'cash_cl', 'caliq_cl', 'ca_cl', 'inv_turnover', 'at_turnover', 'rec_turnover', 'ap_turnover', 'adv_sale', 'staff_sale', 'sale_bev', 'rd_sale', 'sale_be', 'div_ni', 'sale_nwc', 'tax_pi', 'cash_at', 'ni_emp', 'sale_emp', 'sale_emp_gr1', 'emp_gr1', 'ni_inc8q', 'noa_gr1a', 'ppeinv_gr1a', 'lnoa_gr1a', 'capx_gr2', 'saleq_gr1', 'niq_be', 'niq_at', 'niq_be_chg1', 'niq_at_chg1', 'rd5_at', 'dsale_dinv', 'dsale_drec', 'dgp_dsale', 'dsale_dsga', 'saleq_su', 'niq_su', 'capex_abn', 'op_atl1', 'gp_atl1', 'ope_bel1', 'cop_atl1', 'pi_nix', 'ocf_at', 'op_at', 'ocf_at_chg1', 'at_be', 'ocfq_saleq_std', 'niq_saleq_std', 'roeq_be_std', 'roe_be_std', 'tangibility', 'earnings_variability', 'aliq_at', 'f_score', 'o_score', 'z_score', 'intrinsic_value', 'kz_index', 'gpoa_ch5', 'roe_ch5', 'roa_ch5', 'cfoa_ch5', 'gmar_ch5', 'ni_ar1', 'ni_ivol', 'at_me', 'be_me', 'debt_me', 'netdebt_me', 'cash_me', 'sale_me', 'gp_me', 'ebitda_me', 'ebit_me', 'ope_me', 'ni_me', 'nix_me', 'cop_me', 'ocf_me', 'fcf_me', 'div_me', 'eqbb_me', 'eqis_me', 'eqpo_me', 'eqnpo_me', 'eqnetis_me', 'rd_me', 'ival_me', 'at_mev', 'bev_mev', 'ppen_mev', 'be_mev', 'cash_mev', 'sale_mev', 'gp_mev', 'ebitda_mev', 'ebit_mev', 'cop_mev', 'ocf_mev', 'fcf_mev', 'debt_mev', 'pstk_mev', 'debtlt_mev', 'debtst_mev', 'dltnetis_mev', 'dstnetis_mev', 'dbnetis_mev', 'netis_mev', 'fincf_mev', 'aliq_mat', 'eq_dur', 'beta_60m', 'ivol_capm_60m', 'mispricing_mgmt', 'mispricing_perf', 'beta_21d', 'beta_dimson_21d', 'bidaskhl_21d', 'coskew_21d', 'iskew_capm_21d', 'ivol_capm_21d', 'rmax1_21d', 'rmax5_21d', 'rskew_21d', 'rvol_21d', 'rvolhl_21d', 'zero_trades_21d', 'iskew_ff3_21d', 'iskew_hxz4_21d', 'ivol_ff3_21d', 'ivol_hxz4_21d', 'ami_126d', 'dolvol_126d', 'dolvol_var_126d', 'turnover_126d', 'turnover_var_126d', 'zero_trades_126d', 'beta_252d', 'betadown_252d', 'ivol_capm_252d', 'prc_highprc_252d', 'rvol_252d', 'zero_trades_252d', 'corr_1260d', 'betabab_1260d', 'rmax5_rvol_21d', 'age', 'qmj', 'qmj_prof', 'qmj_growth', 'qmj_safety']

In [33]:
id_unique = sorted(data['id'].unique())
print(id_unique)

[np.int64(10026), np.int64(10028), np.int64(10032), np.int64(10044), np.int64(10066), np.int64(10104), np.int64(10107), np.int64(10138), np.int64(10145), np.int64(10158), np.int64(10200), np.int64(10220), np.int64(10252), np.int64(10253), np.int64(10257), np.int64(10258), np.int64(10294), np.int64(10308), np.int64(10318), np.int64(10333), np.int64(10355), np.int64(10382), np.int64(10397), np.int64(10421), np.int64(10443), np.int64(10463), np.int64(10501), np.int64(10516), np.int64(10517), np.int64(10547), np.int64(10550), np.int64(10606), np.int64(10629), np.int64(10645), np.int64(10649), np.int64(10661), np.int64(10693), np.int64(10696), np.int64(10777), np.int64(10779), np.int64(10812), np.int64(10860), np.int64(10866), np.int64(10874), np.int64(10886), np.int64(10890), np.int64(10892), np.int64(10901), np.int64(10932), np.int64(10933), np.int64(10966), np.int64(11006), np.int64(11018), np.int64(11043), np.int64(11144), np.int64(11153), np.int64(11154), np.int64(11174), np.int64(11208), np.int64(11267), np.int64(11275), np.int64(11285), np.int64(11292), np.int64(11293), np.int64(11308), np.int64(11368), np.int64(11369), np.int64(11370), np.int64(11379), np.int64(11394), np.int64(11397), np.int64(11403), np.int64(11404), np.int64(11442), np.int64(11499), np.int64(11511), np.int64(11533), np.int64(11547), np.int64(11565), np.int64(11581), np.int64(11587), np.int64(11593), np.int64(11600), np.int64(11618), np.int64(11628), np.int64(11636), np.int64(11644), np.int64(11654), np.int64(11664), np.int64(11674), np.int64(11691), np.int64(11701), np.int64(11731), np.int64(11748), np.int64(11752), np.int64(11762), np.int64(11775), np.int64(11790), np.int64(11803), np.int64(11809), np.int64(11844), np.int64(11850), np.int64(11884), np.int64(11891), np.int64(11955), np.int64(11990), np.int64(11995), np.int64(12008), np.int64(12009), np.int64(12017), np.int64(12036), np.int64(12049), np.int64(12052), np.int64(12060), np.int64(12062), np.int64(12068), np.int64(12076), np.int64(12078), np.int64(12082), np.int64(12084), np.int64(12146), np.int64(12189), np.int64(12209), np.int64(12211), np.int64(12226), np.int64(12266), np.int64(12308), np.int64(12310), np.int64(12332), np.int64(12345), np.int64(12350), np.int64(12358), np.int64(12360), np.int64(12363), np.int64(12366), np.int64(12369), np.int64(12373), np.int64(12380), np.int64(12391), np.int64(12397), np.int64(12400), np.int64(12411), np.int64(12431), np.int64(12447), np.int64(12449), np.int64(12452), np.int64(12473), np.int64(12476), np.int64(12477), np.int64(12480), np.int64(12487), np.int64(12488), np.int64(12490), np.int64(12495), np.int64(12497), np.int64(12500), np.int64(12515), np.int64(12527), np.int64(12540), np.int64(12558), np.int64(12569), np.int64(12570), np.int64(12573), np.int64(12577), np.int64(12579), np.int64(12583), np.int64(12591), np.int64(12592), np.int64(12615), np.int64(12622), np.int64(12623), np.int64(12629), np.int64(12641), np.int64(12684), np.int64(12781), np.int64(12783), np.int64(12788), np.int64(12789), np.int64(12796), np.int64(12799), np.int64(12840), np.int64(12872), np.int64(12877), np.int64(12880), np.int64(12890), np.int64(12905), np.int64(12913), np.int64(12920), np.int64(12927), np.int64(12928), np.int64(12981), np.int64(12982), np.int64(12994), np.int64(13006), np.int64(13007), np.int64(13019), np.int64(13035), np.int64(13046), np.int64(13085), np.int64(13103), np.int64(13105), np.int64(13108), np.int64(13111), np.int64(13116), np.int64(13124), np.int64(13142), np.int64(13159), np.int64(13168), np.int64(13180), np.int64(13181), np.int64(13188), np.int64(13196), np.int64(13198), np.int64(13202), np.int64(13210), np.int64(13244), np.int64(13249), np.int64(13253), np.int64(13260), np.int64(13278), np.int64(13279), np.int64(13284), np.int64(13302), np.int64(13303), np.int64(13305), np.int64(13318), np.int64(13321), np.int64(13323), np.int64(13324), np.int64(13325), np.int64(13326), np.int64(13328), np.int64(13337), np.int64(13343), np.int64(13350), np.int64(13353), np.int64(13356), np.int64(13369), np.int64(13379), np.int64(13399), np.int64(13403), np.int64(13407), np.int64(13410), np.int64(13411), np.int64(13412), np.int64(13447), np.int64(13452), np.int64(13455), np.int64(13508), np.int64(13511), np.int64(13520), np.int64(13527), np.int64(13528), np.int64(13534), np.int64(13543), np.int64(13545), np.int64(13547), np.int64(13548), np.int64(13559), np.int64(13561), np.int64(13563), np.int64(13577), np.int64(13579), np.int64(13583), np.int64(13586), np.int64(13599), np.int64(13600), np.int64(13604), np.int64(13610), np.int64(13621), np.int64(13622), np.int64(13625), np.int64(13628), np.int64(13634), np.int64(13641), np.int64(13652), np.int64(13687), np.int64(13688), np.int64(13693), np.int64(13694), np.int64(13704), np.int64(13706), np.int64(13712), np.int64(13721), np.int64(13730), np.int64(13739), np.int64(13743), np.int64(13748), np.int64(13750), np.int64(13751), np.int64(13757), np.int64(13760), np.int64(13763), np.int64(13766), np.int64(13769), np.int64(13777), np.int64(13786), np.int64(13788), np.int64(13796), np.int64(13797), np.int64(13798), np.int64(13802), np.int64(13812), np.int64(13816), np.int64(13820), np.int64(13825), np.int64(13828), np.int64(13837), np.int64(13844), np.int64(13856), np.int64(13860), np.int64(13862), np.int64(13863), np.int64(13870), np.int64(13877), np.int64(13878), np.int64(13883), np.int64(13901), np.int64(13904), np.int64(13908), np.int64(13911), np.int64(13917), np.int64(13918), np.int64(13919), np.int64(13921), np.int64(13928), np.int64(13930), np.int64(13935), np.int64(13936), np.int64(13939), np.int64(13947), np.int64(13949), np.int64(13954), np.int64(13956), np.int64(13959), np.int64(13962), np.int64(13963), np.int64(13964), np.int64(13965), np.int64(13967), np.int64(13969), np.int64(13976), np.int64(13978), np.int64(13983), np.int64(14008), np.int64(14030), np.int64(14033), np.int64(14044), np.int64(14045), np.int64(14051), np.int64(14056), np.int64(14060), np.int64(14072), np.int64(14076), np.int64(14088), np.int64(14089), np.int64(14092), np.int64(14093), np.int64(14097), np.int64(14102), np.int64(14107), np.int64(14127), np.int64(14133), np.int64(14135), np.int64(14136), np.int64(14137), np.int64(14141), np.int64(14144), np.int64(14145), np.int64(14158), np.int64(14166), np.int64(14169), np.int64(14172), np.int64(14177), np.int64(14179), np.int64(14182), np.int64(14185), np.int64(14213), np.int64(14221), np.int64(14229), np.int64(14231), np.int64(14235), np.int64(14239), np.int64(14245), np.int64(14257), np.int64(14258), np.int64(14263), np.int64(14273), np.int64(14274), np.int64(14276), np.int64(14277), np.int64(14296), np.int64(14297), np.int64(14300), np.int64(14301), np.int64(14310), np.int64(14313), np.int64(14316), np.int64(14317), np.int64(14318), np.int64(14325), np.int64(14326), np.int64(14328), np.int64(14329), np.int64(14336), np.int64(14338), np.int64(14339), np.int64(14353), np.int64(14358), np.int64(14359), np.int64(14379), np.int64(14401), np.int64(14406), np.int64(14419), np.int64(14422), np.int64(14423), np.int64(14431), np.int64(14432), np.int64(14434), np.int64(14435), np.int64(14436), np.int64(14440), np.int64(14442), np.int64(14444), np.int64(14452), np.int64(14456), np.int64(14459), np.int64(14466), np.int64(14467), np.int64(14468), np.int64(14469), np.int64(14472), np.int64(14479), np.int64(14487), np.int64(14490), np.int64(14493), np.int64(14495), np.int64(14497), np.int64(14503), np.int64(14516), np.int64(14521), np.int64(14523), np.int64(14526), np.int64(14531), np.int64(14532), np.int64(14535), np.int64(14536), np.int64(14540), np.int64(14541), np.int64(14542), np.int64(14543), np.int64(14544), np.int64(14545), np.int64(14546), np.int64(14547), np.int64(14548), np.int64(14550), np.int64(14551), np.int64(14554), np.int64(14556), np.int64(14558), np.int64(14574), np.int64(14579), np.int64(14580), np.int64(14591), np.int64(14593), np.int64(14596), np.int64(14599), np.int64(14601), np.int64(14603), np.int64(14604), np.int64(14607), np.int64(14608), np.int64(14609), np.int64(14610), np.int64(14615), np.int64(14617), np.int64(14619), np.int64(14625), np.int64(14632), np.int64(14636), np.int64(14642), np.int64(14645), np.int64(14647), np.int64(14650), np.int64(14653), np.int64(14661), np.int64(14663), np.int64(14668), np.int64(14670), np.int64(14674), np.int64(14677), np.int64(14682), np.int64(14684), np.int64(14687), np.int64(14688), np.int64(14689), np.int64(14690), np.int64(14691), np.int64(14694), np.int64(14702), np.int64(14708), np.int64(14711), np.int64(14714), np.int64(14715), np.int64(14716), np.int64(14720), np.int64(14759), np.int64(14763), np.int64(14773), np.int64(14776), np.int64(14778), np.int64(14782), np.int64(14785), np.int64(14786), np.int64(14790), np.int64(14791), np.int64(14795), np.int64(14797), np.int64(14803), np.int64(14807), np.int64(14810), np.int64(14811), np.int64(14812), np.int64(14813), np.int64(14815), np.int64(14816), np.int64(14818), np.int64(14820), np.int64(14822), np.int64(14823), np.int64(14826), np.int64(14828), np.int64(14830), np.int64(14852), np.int64(14855), np.int64(14862), np.int64(14865), np.int64(14877), np.int64(14879), np.int64(14882), np.int64(14884), np.int64(14889), np.int64(14919), np.int64(14923), np.int64(14924), np.int64(14925), np.int64(14928), np.int64(14932), np.int64(14934), np.int64(14935), np.int64(14936), np.int64(14937), np.int64(14939), np.int64(14941), np.int64(14942), np.int64(14943), np.int64(14944), np.int64(14951), np.int64(14953), np.int64(14960), np.int64(14970), np.int64(14973), np.int64(14983), np.int64(14985), np.int64(14987), np.int64(14988), np.int64(14991), np.int64(15014), np.int64(15015), np.int64(15016), np.int64(15020), np.int64(15022), np.int64(15028), np.int64(15046), np.int64(15053), np.int64(15054), np.int64(15056), np.int64(15057), np.int64(15058), np.int64(15059), np.int64(15062), np.int64(15064), np.int64(15065), np.int64(15067), np.int64(15069), np.int64(15070), np.int64(15072), np.int64(15084), np.int64(15087), np.int64(15089), np.int64(15092), np.int64(15113), np.int64(15119), np.int64(15127), np.int64(15129), np.int64(15132), np.int64(15133), np.int64(15139), np.int64(15145), np.int64(15167), np.int64(15168), np.int64(15169), np.int64(15170), np.int64(15172), np.int64(15177), np.int64(15178), np.int64(15184), np.int64(15186), np.int64(15198), np.int64(15202), np.int64(15203), np.int64(15215), np.int64(15219), np.int64(15221), np.int64(15222), np.int64(15226), np.int64(15254), np.int64(15264), np.int64(15268), np.int64(15271), np.int64(15272), np.int64(15273), np.int64(15277), np.int64(15278), np.int64(15284), np.int64(15285), np.int64(15286), np.int64(15287), np.int64(15291), np.int64(15293), np.int64(15294), np.int64(15295), np.int64(15297), np.int64(15302), np.int64(15303), np.int64(15305), np.int64(15313), np.int64(15315), np.int64(15318), np.int64(15331), np.int64(15332), np.int64(15336), np.int64(15351), np.int64(15358), np.int64(15371), np.int64(15375), np.int64(15378), np.int64(15381), np.int64(15382), np.int64(15383), np.int64(15395), np.int64(15396), np.int64(15397), np.int64(15398), np.int64(15400), np.int64(15408), np.int64(15409), np.int64(15410), np.int64(15416), np.int64(15417), np.int64(15423), np.int64(15429), np.int64(15431), np.int64(15432), np.int64(15433), np.int64(15436), np.int64(15440), np.int64(15452), np.int64(15454), np.int64(15456), np.int64(15457), np.int64(15478), np.int64(15488), np.int64(15489), np.int64(15490), np.int64(15491), np.int64(15493), np.int64(15506), np.int64(15508), np.int64(15510), np.int64(15525), np.int64(15527), np.int64(15530), np.int64(15533), np.int64(15534), np.int64(15535), np.int64(15537), np.int64(15539), np.int64(15540), np.int64(15541), np.int64(15542), np.int64(15543), np.int64(15546), np.int64(15579), np.int64(15580), np.int64(15582), np.int64(15585), np.int64(15597), np.int64(15623), np.int64(15627), np.int64(15631), np.int64(15636), np.int64(15639), np.int64(15642), np.int64(15643), np.int64(15645), np.int64(15649), np.int64(15650), np.int64(15651), np.int64(15653), np.int64(15654), np.int64(15658), np.int64(15662), np.int64(15664), np.int64(15694), np.int64(15702), np.int64(15707), np.int64(15720), np.int64(15724), np.int64(15729), np.int64(15735), np.int64(15775), np.int64(15776), np.int64(15779), np.int64(15782), np.int64(15784), np.int64(15787), np.int64(15789), np.int64(15793), np.int64(15795), np.int64(15796), np.int64(15802), np.int64(15826), np.int64(15831), np.int64(15833), np.int64(15837), np.int64(15838), np.int64(15840), np.int64(15847), np.int64(15850), np.int64(15853), np.int64(15854), np.int64(15856), np.int64(15857), np.int64(15859), np.int64(15860), np.int64(15862), np.int64(15863), np.int64(15902), np.int64(15906), np.int64(15909), np.int64(15913), np.int64(15914), np.int64(15920), np.int64(15937), np.int64(15943), np.int64(15948), np.int64(15950), np.int64(15960), np.int64(15961), np.int64(15976), np.int64(15980), np.int64(15995), np.int64(15998), np.int64(15999), np.int64(16000), np.int64(16005), np.int64(16007), np.int64(16008), np.int64(16012), np.int64(16019), np.int64(16020), np.int64(16021), np.int64(16043), np.int64(16044), np.int64(16048), np.int64(16049), np.int64(16062), np.int64(16063), np.int64(16064), np.int64(16066), np.int64(16070), np.int64(16076), np.int64(16082), np.int64(16083), np.int64(16084), np.int64(16086), np.int64(16087), np.int64(16090), np.int64(16097), np.int64(16099), np.int64(16104), np.int64(16108), np.int64(16111), np.int64(16119), np.int64(16126), np.int64(16140), np.int64(16145), np.int64(16146), np.int64(16156), np.int64(16164), np.int64(16171), np.int64(16179), np.int64(16181), np.int64(16182), np.int64(16186), np.int64(16188), np.int64(16247), np.int64(16250), np.int64(16252), np.int64(16253), np.int64(16255), np.int64(16260), np.int64(16263), np.int64(16276), np.int64(16277), np.int64(16281), np.int64(16284), np.int64(16285), np.int64(16287), np.int64(16290), np.int64(16304), np.int64(16309), np.int64(16310), np.int64(16318), np.int64(16319), np.int64(16338), np.int64(16339), np.int64(16341), np.int64(16342), np.int64(16343), np.int64(16347), np.int64(16376), np.int64(16377), np.int64(16381), np.int64(16383), np.int64(16386), np.int64(16392), np.int64(16393), np.int64(16400), np.int64(16401), np.int64(16431), np.int64(16432), np.int64(16434), np.int64(16436), np.int64(16437), np.int64(16442), np.int64(16448), np.int64(16454), np.int64(16458), np.int64(16463), np.int64(16465), np.int64(16466), np.int64(16471), np.int64(16472), np.int64(16473), np.int64(16479), np.int64(16495), np.int64(16497), np.int64(16498), np.int64(16499), np.int64(16505), np.int64(16522), np.int64(16524), np.int64(16525), np.int64(16528), np.int64(16532), np.int64(16533), np.int64(16536), np.int64(16537), np.int64(16538), np.int64(16541), np.int64(16542), np.int64(16543), np.int64(16545), np.int64(16548), np.int64(16554), np.int64(16555), np.int64(16560), np.int64(16562), np.int64(16591), np.int64(16592), np.int64(16594), np.int64(16595), np.int64(16597), np.int64(16600), np.int64(16603), np.int64(16611), np.int64(16613), np.int64(16617), np.int64(16625), np.int64(16626), np.int64(16630), np.int64(16631), np.int64(16632), np.int64(16633), np.int64(16638), np.int64(16641), np.int64(16648), np.int64(16649), np.int64(16650), np.int64(16653), np.int64(16655), np.int64(16660), np.int64(16664), np.int64(16667), np.int64(16668), np.int64(16670), np.int64(16671), np.int64(16673), np.int64(16675), np.int64(16678), np.int64(16680), np.int64(16681), np.int64(16689), np.int64(16692), np.int64(16693), np.int64(16696), np.int64(16697), np.int64(16698), np.int64(16703), np.int64(16705), np.int64(16709), np.int64(16710), np.int64(16711), np.int64(16712), np.int64(16736), np.int64(16737), np.int64(16738), np.int64(16746), np.int64(16749), np.int64(16750), np.int64(16753), np.int64(16756), np.int64(16765), np.int64(16771), np.int64(16773), np.int64(16776), np.int64(16778), np.int64(16779), np.int64(16781), np.int64(16784), np.int64(16788), np.int64(16792), np.int64(16793), np.int64(16794), np.int64(16795), np.int64(16802), np.int64(16805), np.int64(16816), np.int64(16818), np.int64(16819), np.int64(16820), np.int64(16824), np.int64(16827), np.int64(16828), np.int64(16829), np.int64(16836), np.int64(16849), np.int64(16851), np.int64(16853), np.int64(16857), np.int64(16866), np.int64(16874), np.int64(16877), np.int64(16880), np.int64(16883), np.int64(16887), np.int64(16894), np.int64(16895), np.int64(16903), np.int64(16905), np.int64(16920), np.int64(16921), np.int64(16922), np.int64(16923), np.int64(16924), np.int64(16927), np.int64(16928), np.int64(16931), np.int64(16932), np.int64(16937), np.int64(16961), np.int64(16963), np.int64(16964), np.int64(16965), np.int64(16967), np.int64(16968), np.int64(16971), np.int64(16974), np.int64(16975), np.int64(16976), np.int64(16981), np.int64(16982), np.int64(16987), np.int64(16989), np.int64(16990), np.int64(16991), np.int64(16992), np.int64(16995), np.int64(16999), np.int64(17000), np.int64(17005), np.int64(17032), np.int64(17033), np.int64(17034), np.int64(17036), np.int64(17038), np.int64(17039), np.int64(17041), np.int64(17043), np.int64(17044), np.int64(17045), np.int64(17091), np.int64(17093), np.int64(17103), np.int64(17104), np.int64(17105), np.int64(17106), np.int64(17107), np.int64(17108), np.int64(17109), np.int64(17115), np.int64(17116), np.int64(17117), np.int64(17120), np.int64(17121), np.int64(17122), np.int64(17125), np.int64(17126), np.int64(17130), np.int64(17131), np.int64(17133), np.int64(17134), np.int64(17135), np.int64(17137), np.int64(17140), np.int64(17141), np.int64(17144), np.int64(17147), np.int64(17148), np.int64(17151), np.int64(17155), np.int64(17157), np.int64(17178), np.int64(17200), np.int64(17221), np.int64(17223), np.int64(17226), np.int64(17227), np.int64(17250), np.int64(17251), np.int64(17252), np.int64(17254), np.int64(17262), np.int64(17263), np.int64(17266), np.int64(17270), np.int64(17271), np.int64(17272), np.int64(17281), np.int64(17309), np.int64(17310), np.int64(17313), np.int64(17315), np.int64(17316), np.int64(17317), np.int64(17318), np.int64(17323), np.int64(17324), np.int64(17325), np.int64(17326), np.int64(17327), np.int64(17330), np.int64(17332), np.int64(17341), np.int64(17342), np.int64(17343), np.int64(17344), np.int64(17345), np.int64(17349), np.int64(17350), np.int64(17351), np.int64(17354), np.int64(17357), np.int64(17358), np.int64(17359), np.int64(17360), np.int64(17361), np.int64(17365), np.int64(17366), np.int64(17367), np.int64(17368), np.int64(17369), np.int64(17370), np.int64(17372), np.int64(17373), np.int64(17374), np.int64(17381), np.int64(17382), np.int64(17444), np.int64(17478), np.int64(17672), np.int64(17676), np.int64(17677), np.int64(17678), np.int64(17679), np.int64(17683), np.int64(17684), np.int64(17685), np.int64(17688), np.int64(17690), np.int64(17691), np.int64(17693), np.int64(17696), np.int64(17700), np.int64(17701), np.int64(17726), np.int64(17743), np.int64(17750), np.int64(17778), np.int64(17782), np.int64(17783), np.int64(17787), np.int64(17794), np.int64(17797), np.int64(17799), np.int64(17800), np.int64(17801), np.int64(17803), np.int64(17809), np.int64(17812), np.int64(17813), np.int64(17816), np.int64(17817), np.int64(17818), np.int64(17821), np.int64(17825), np.int64(17827), np.int64(17830), np.int64(17854), np.int64(17864), np.int64(17867), np.int64(17869), np.int64(17871), np.int64(17875), np.int64(17876), np.int64(17877), np.int64(17879), np.int64(17880), np.int64(17884), np.int64(17885), np.int64(17887), np.int64(17889), np.int64(17890), np.int64(17891), np.int64(17892), np.int64(17893), np.int64(17895), np.int64(17898), np.int64(17901), np.int64(17906), np.int64(17907), np.int64(17908), np.int64(17920), np.int64(17929), np.int64(17942), np.int64(17944), np.int64(17948), np.int64(17949), np.int64(17951), np.int64(17955), np.int64(17956), np.int64(17957), np.int64(17959), np.int6

In [34]:
# 'market_equity', 'ret_exc', 'ret_local', 'me' contains forward information
# data = data.drop(columns=['market_equity', 'ret_exc', 'ret_local', 'me'])
data = data.drop(columns=['market_equity', 'ret_exc', 'ret_local', 'me', "ret_1_0", "ret"])

In [35]:
# size grp: we probably don't want micro and nano cap because they are illiquid and hence incur high t-cost or artificial high return
print(data['size_grp'].unique())
data = data[~data['size_grp'].isin(['nano', 'micro', np.nan])]

<StringArray>
['small', 'micro', 'large', 'nano', 'mega', nan]
Length: 6, dtype: str

In [36]:
# if CRSP exists, use CRSP as the main observation.
data = data[data['obs_main'] == 1]
# only regular common shares
data = data[data['common'] == 1]
# only includes stocks listed on the primary/main exchange.
data = data[data['exch_main'] == 1]
# non-primary listings
data = data[data['primary_sec'] == 1]
data

,id,date,eom,source_crsp,size_grp,obs_main,exch_main,primary_sec,gvkey,iid,...,rvol_252d,zero_trades_252d,corr_1260d,betabab_1260d,rmax5_rvol_21d,age,qmj,qmj_prof,qmj_growth,qmj_safety
0,10026,20240131,20240131,1,small,1,1,1,12825.0,1.0,...,NaN,NaN,NaN,NaN,NaN,469,1.284129,1.204025,-0.067640,1.448983
1,10026,20240229,20240229,1,small,1,1,1,12825.0,1.0,...,NaN,NaN,NaN,NaN,NaN,470,1.282924,1.198607,-0.075588,1.449240
2,10026,20240328,20240331,1,small,1,1,1,12825.0,1.0,...,NaN,NaN,NaN,NaN,NaN,471,1.280630,1.196231,-0.075454,1.447640
3,10026,20240430,20240430,1,small,1,1,1,12825.0,1.0,...,NaN,NaN,NaN,NaN,NaN,472,1.423064,1.291237,0.204842,1.430103
4,10026,20240531,20240531,1,small,1,1,1,12825.0,1.0,...,NaN,NaN,NaN,NaN,NaN,473,1.426046,1.291984,0.203015,1.429422
5,10026,20240628,20240630,1,small,1,1,1,12825.0,1.0,...,0.019756,0.005127,NaN,NaN,0.663480,474,1.424819,1.285306,0.200853,1.424767
6,10026,20240731,20240731,1,small,1,1,1,12825.0,1.0,...,0.018842,0.005171,NaN,NaN,0.774694,475,1.375874,1.290799,0.165077,1.357295
7,10026,20240830,20240831,1,small,1,1,1,12825.0,1.0,...,0.019098,0.005187,NaN,NaN,1.458593,476,1.359689,1.282651,0.150416,1.352312
8,10026,20240930,20240930,1,small,1,1,1,12825.0,1.0,...,0.018334,0.005257,NaN,NaN,0.690187,477,1.361963,1.281207,0.150217,1.353159
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2332902,135685901,20251231,20251231,0,mega,1,1,1,356859.0,1.0,...,NaN,NaN,NaN,NaN,NaN,36,NaN,NaN,NaN,NaN
2332903,136691101,20250630,20250630,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,42,NaN,NaN,NaN,NaN
2332904,136691101,20250731,20250731,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,43,NaN,NaN,NaN,NaN
2332905,136691101,20250829,20250831,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,44,NaN,NaN,NaN,NaN
2332906,136691101,20250930,20250930,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,45,NaN,NaN,NaN,NaN
2332907,136691101,20251031,20251031,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,46,NaN,NaN,NaN,NaN
2332908,136691101,20251128,20251130,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,47,NaN,NaN,NaN,NaN
2332909,136691101,20251231,20251231,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,48,NaN,NaN,NaN,NaN
2332910,136935001,20251231,20251231,0,mega,1,1,1,369350.0,1.0,...,NaN,NaN,NaN,NaN,NaN,36,NaN,NaN,NaN,NaN

In [37]:
# factor_df['date'] = pd.to_datetime(factor_df['date'].astype(str), format='%Y%m%d')
# factor_df['date'] = factor_df['date'].apply(lambda x: x.strftime('%Y%m%d'))
# factor_df['date'] = factor_df['date'].astype(int)
data['date'] = pd.to_datetime(data['date'], format='%Y%m%d')
start_dt = data['date'].min()
end_dt = data['date'].max()
print ("Date Range: %s --> %s"%(start_dt,end_dt))
date_unique = sorted(data['date'].unique())

Date Range: 1981-01-31 00:00:00 --> 2025-12-31 00:00:00

In [38]:
data['eom'] = pd.to_datetime(data['eom'], format='%Y%m%d')
start_eom = data['eom'].min()
end_eom = data['eom'].max()
print ("EOM Range: %s --> %s"%(start_eom,end_eom))
eom_unique = sorted(data['eom'].unique())

EOM Range: 1981-01-31 00:00:00 --> 2025-12-31 00:00:00

In [39]:
for eom in eom_unique:
    print(eom)

1981-01-31 00:00:00
1981-02-28 00:00:00
1981-03-31 00:00:00
1981-04-30 00:00:00
1981-05-31 00:00:00
1981-06-30 00:00:00
1981-07-31 00:00:00
1981-08-31 00:00:00
1981-09-30 00:00:00
1981-10-31 00:00:00
1981-11-30 00:00:00
1981-12-31 00:00:00
1982-01-31 00:00:00
1982-02-28 00:00:00
1982-03-31 00:00:00
1982-04-30 00:00:00
1982-05-31 00:00:00
1982-06-30 00:00:00
1982-07-31 00:00:00
1982-08-31 00:00:00
1982-09-30 00:00:00
1982-10-31 00:00:00
1982-11-30 00:00:00
1982-12-31 00:00:00
1983-01-31 00:00:00
1983-02-28 00:00:00
1983-03-31 00:00:00
1983-04-30 00:00:00
1983-05-31 00:00:00
1983-06-30 00:00:00
1983-07-31 00:00:00
1983-08-31 00:00:00
1983-09-30 00:00:00
1983-10-31 00:00:00
1983-11-30 00:00:00
1983-12-31 00:00:00
1984-01-31 00:00:00
1984-02-29 00:00:00
1984-03-31 00:00:00
1984-04-30 00:00:00
1984-05-31 00:00:00
1984-06-30 00:00:00
1984-07-31 00:00:00
1984-08-31 00:00:00
1984-09-30 00:00:00
1984-10-31 00:00:00
1984-11-30 00:00:00
1984-12-31 00:00:00
1985-01-31 00:00:00
1985-02-28 00:00:00
1985-03-31 00:00:00
1985-04-30 00:00:00
1985-05-31 00:00:00
1985-06-30 00:00:00
1985-07-31 00:00:00
1985-08-31 00:00:00
1985-09-30 00:00:00
1985-10-31 00:00:00
1985-11-30 00:00:00
1985-12-31 00:00:00
1986-01-31 00:00:00
1986-02-28 00:00:00
1986-03-31 00:00:00
1986-04-30 00:00:00
1986-05-31 00:00:00
1986-06-30 00:00:00
1986-07-31 00:00:00
1986-08-31 00:00:00
1986-09-30 00:00:00
1986-10-31 00:00:00
1986-11-30 00:00:00
1986-12-31 00:00:00
1987-01-31 00:00:00
1987-02-28 00:00:00
1987-03-31 00:00:00
1987-04-30 00:00:00
1987-05-31 00:00:00
1987-06-30 00:00:00
1987-07-31 00:00:00
1987-08-31 00:00:00
1987-09-30 00:00:00
1987-10-31 00:00:00
1987-11-30 00:00:00
1987-12-31 00:00:00
1988-01-31 00:00:00
1988-02-29 00:00:00
1988-03-31 00:00:00
1988-04-30 00:00:00
1988-05-31 00:00:00
1988-06-30 00:00:00
1988-07-31 00:00:00
1988-08-31 00:00:00
1988-09-30 00:00:00
1988-10-31 00:00:00
1988-11-30 00:00:00
1988-12-31 00:00:00
1989-01-31 00:00:00
1989-02-28 00:00:00
1989-03-31 00:00:00
1989-04-30 00:00:00
1989-05-31 00:00:00
1989-06-30 00:00:00
1989-07-31 00:00:00
1989-08-31 00:00:00
1989-09-30 00:00:00
1989-10-31 00:00:00
1989-11-30 00:00:00
1989-12-31 00:00:00
1990-01-31 00:00:00
1990-02-28 00:00:00
1990-03-31 00:00:00
1990-04-30 00:00:00
1990-05-31 00:00:00
1990-06-30 00:00:00
1990-07-31 00:00:00
1990-08-31 00:00:00
1990-09-30 00:00:00
1990-10-31 00:00:00
1990-11-30 00:00:00
1990-12-31 00:00:00
1991-01-31 00:00:00
1991-02-28 00:00:00
1991-03-31 00:00:00
1991-04-30 00:00:00
1991-05-31 00:00:00
1991-06-30 00:00:00
1991-07-31 00:00:00
1991-08-31 00:00:00
1991-09-30 00:00:00
1991-10-31 00:00:00
1991-11-30 00:00:00
1991-12-31 00:00:00
1992-01-31 00:00:00
1992-02-29 00:00:00
1992-03-31 00:00:00
1992-04-30 00:00:00
1992-05-31 00:00:00
1992-06-30 00:00:00
1992-07-31 00:00:00
1992-08-31 00:00:00
1992-09-30 00:00:00
1992-10-31 00:00:00
1992-11-30 00:00:00
1992-12-31 00:00:00
1993-01-31 00:00:00
1993-02-28 00:00:00
1993-03-31 00:00:00
1993-04-30 00:00:00
1993-05-31 00:00:00
1993-06-30 00:00:00
1993-07-31 00:00:00
1993-08-31 00:00:00
1993-09-30 00:00:00
1993-10-31 00:00:00
1993-11-30 00:00:00
1993-12-31 00:00:00
1994-01-31 00:00:00
1994-02-28 00:00:00
1994-03-31 00:00:00
1994-04-30 00:00:00
1994-05-31 00:00:00
1994-06-30 00:00:00
1994-07-31 00:00:00
1994-08-31 00:00:00
1994-09-30 00:00:00
1994-10-31 00:00:00
1994-11-30 00:00:00
1994-12-31 00:00:00
1995-01-31 00:00:00
1995-02-28 00:00:00
1995-03-31 00:00:00
1995-04-30 00:00:00
1995-05-31 00:00:00
1995-06-30 00:00:00
1995-07-31 00:00:00
1995-08-31 00:00:00
1995-09-30 00:00:00
1995-10-31 00:00:00
1995-11-30 00:00:00
1995-12-31 00:00:00
1996-01-31 00:00:00
1996-02-29 00:00:00
1996-03-31 00:00:00
1996-04-30 00:00:00
1996-05-31 00:00:00
1996-06-30 00:00:00
1996-07-31 00:00:00
1996-08-31 00:00:00
1996-09-30 00:00:00
1996-10-31 00:00:00
1996-11-30 00:00:00
1996-12-31 00:00:00
1997-01-31 00:00:00
1997-02-28 00:00:00
1997-03-31 00:00:00
1997-04-30 00:00:00
1997-05-31 00:00:00
1997-06-30 00:00:00
1997-07-31 00:00:00
1997-08-31 00:00:00
1997-09-30 00:00:00
1997-10-31 00:00:00
1997-11-30 00:00:00
1997-12-31 00:00:00
1998-01-31 00:00:00
1998-02-28 00:00:00
1998-03-31 00:00:00
1998-04-30 00:00:00
1998-05-31 00:00:00
1998-06-30 00:00:00
1998-07-31 00:00:00
1998-08-31 00:00:00
1998-09-30 00:00:00
1998-10-31 00:00:00
1998-11-30 00:00:00
1998-12-31 00:00:00
1999-01-31 00:00:00
1999-02-28 00:00:00
1999-03-31 00:00:00
1999-04-30 00:00:00
1999-05-31 00:00:00
1999-06-30 00:00:00
1999-07-31 00:00:00
1999-08-31 00:00:00
1999-09-30 00:00:00
1999-10-31 00:00:00
1999-11-30 00:00:00
1999-12-31 00:00:00
2000-01-31 00:00:00
2000-02-29 00:00:00
2000-03-31 00:00:00
2000-04-30 00:00:00
2000-05-31 00:00:00
2000-06-30 00:00:00
2000-07-31 00:00:00
2000-08-31 00:00:00
2000-09-30 00:00:00
2000-10-31 00:00:00
2000-11-30 00:00:00
2000-12-31 00:00:00
2001-01-31 00:00:00
2001-02-28 00:00:00
2001-03-31 00:00:00
2001-04-30 00:00:00
2001-05-31 00:00:00
2001-06-30 00:00:00
2001-07-31 00:00:00
2001-08-31 00:00:00
2001-09-30 00:00:00
2001-10-31 00:00:00
2001-11-30 00:00:00
2001-12-31 00:00:00
2002-01-31 00:00:00
2002-02-28 00:00:00
2002-03-31 00:00:00
2002-04-30 00:00:00
2002-05-31 00:00:00
2002-06-30 00:00:00
2002-07-31 00:00:00
2002-08-31 00:00:00
2002-09-30 00:00:00
2002-10-31 00:00:00
2002-11-30 00:00:00
2002-12-31 00:00:00
2003-01-31 00:00:00
2003-02-28 00:00:00
2003-03-31 00:00:00
2003-04-30 00:00:00
2003-05-31 00:00:00
2003-06-30 00:00:00
2003-07-31 00:00:00
2003-08-31 00:00:00
2003-09-30 00:00:00
2003-10-31 00:00:00
2003-11-30 00:00:00
2003-12-31 00:00:00
2004-01-31 00:00:00
2004-02-29 00:00:00
2004-03-31 00:00:00
2004-04-30 00:00:00
2004-05-31 00:00:00
2004-06-30 00:00:00
2004-07-31 00:00:00
2004-08-31 00:00:00
2004-09-30 00:00:00
2004-10-31 00:00:00
2004-11-30 00:00:00
2004-12-31 00:00:00
2005-01-31 00:00:00
2005-02-28 00:00:00
2005-03-31 00:00:00
2005-04-30 00:00:00
2005-05-31 00:00:00
2005-06-30 00:00:00
2005-07-31 00:00:00
2005-08-31 00:00:00
2005-09-30 00:00:00
2005-10-31 00:00:00
2005-11-30 00:00:00
2005-12-31 00:00:00
2006-01-31 00:00:00
2006-02-28 00:00:00
2006-03-31 00:00:00
2006-04-30 00:00:00
2006-05-31 00:00:00
2006-06-30 00:00:00
2006-07-31 00:00:00
2006-08-31 00:00:00
2006-09-30 00:00:00
2006-10-31 00:00:00
2006-11-30 00:00:00
2006-12-31 00:00:00
2007-01-31 00:00:00
2007-02-28 00:00:00
2007-03-31 00:00:00
2007-04-30 00:00:00
2007-05-31 00:00:00
2007-06-30 00:00:00
2007-07-31 00:00:00
2007-08-31 00:00:00
2007-09-30 00:00:00
2007-10-31 00:00:00
2007-11-30 00:00:00
2007-12-31 00:00:00
2008-01-31 00:00:00
2008-02-29 00:00:00
2008-03-31 00:00:00
2008-04-30 00:00:00
2008-05-31 00:00:00
2008-06-30 00:00:00
2008-07-31 00:00:00
2008-08-31 00:00:00
2008-09-30 00:00:00
2008-10-31 00:00:00
2008-11-30 00:00:00
2008-12-31 00:00:00
2009-01-31 00:00:00
2009-02-28 00:00:00
2009-03-31 00:00:00
2009-04-30 00:00:00
2009-05-31 00:00:00
2009-06-30 00:00:00
2009-07-31 00:00:00
2009-08-31 00:00:00
2009-09-30 00:00:00
2009-10-31 00:00:00
2009-11-30 00:00:00
2009-12-31 00:00:00
2010-01-31 00:00:00
2010-02-28 00:00:00
2010-03-31 00:00:00
2010-04-30 00:00:00
2010-05-31 00:00:00
2010-06-30 00:00:00
2010-07-31 00:00:00
2010-08-31 00:00:00
2010-09-30 00:00:00
2010-10-31 00:00:00
2010-11-30 00:00:00
2010-12-31 00:00:00
2011-01-31 00:00:00
2011-02-28 00:00:00
2011-03-31 00:00:00
2011-04-30 00:00:00
2011-05-31 00:00:00
2011-06-30 00:00:00
2011-07-31 00:00:00
2011-08-31 00:00:00
2011-09-30 00:00:00
2011-10-31 00:00:00
2011-11-30 00:00:00
2011-12-31 00:00:00
2012-01-31 00:00:00
2012-02-29 00:00:00
2012-03-31 00:00:00
2012-04-30 00:00:00
2012-05-31 00:00:00
2012-06-30 00:00:00
2012-07-31 00:00:00
2012-08-31 00:00:00
2012-09-30 00:00:00
2012-10-31 00:00:00
2012-11-30 00:00:00
2012-12-31 00:00:00
2013-01-31 00:00:00
2013-02-28 00:00:00
2013-03-31 00:00:00
2013-04-30 00:00:00
2013-05-31 00:00:00
2013-06-30 00:00:00
2013-07-31 00:00:00
2013-08-31 00:00:00
2013-09-30 00:00:00
2013-10-31 00:00:00
2013-11-30 00:00:00
2013-12-31 00:00:00
2014-01-31 00:00:00
2014-02-28 00:00:00
2014-03-31 00:00:00
2014-04-30 00:00:00
2014-05-31 00:00:00
2014-06-30 00:00:00
2014-07-31 00:00:00
2014-08-31 00:00:00
2014-09-30 00:00:00
2014-10-31 00:00:00
2014-11-30 00:00:00
2014-12-31 00:00:00
2015-01-31 00:00:00
2015-02-28 00:00:00
2015-03-31 00:00:00
2015-04-30 00:00:00
2015-05-31 00:00:00
2015-06-30 00:00:00
2015-07-31 00:00:00
2015-08-31 00:00:00
2015-09-30 00:00:00
2015-10-31 00:00:00
2015-11-30 00:00:00
2015-12-31 00:00:00
2016-01-31 00:00:00
2016-02-29 00:00:00
2016-03-31 00:00:00
2016-04-30 00:00:00
2016-05-31 00:00:00
2016-06-30 00:00:00
2016-07-31 00:00:00
2016-08-31 00:00:00
2016-09-30 00:00:00
2016-10-31 00:00:00
2016-11-30 00:00:00
2016-12-31 00:00:00
2017-01-31 00:00:00
2017-02-28 00:00:00
2017-03-31 00:00:00
2017-04-30 00:00:00
2017-05-31 00:00:00
2017-06-30 00:00:00
2017-07-31 00:00:00
2017-08-31 00:00:00
2017-09-30 00:00:00
2017-10-31 00:00:00
2017-11-30 00:00:00
2017-12-31 00:00:00
2018-01-31 00:00:00
2018-02-28 00:00:00
2018-03-31 00:00:00
2018-04-30 00:00:00
2018-05-31 00:00:00
2018-06-30 00:00:00
2018-07-31 00:00:00
2018-08-31 00:00:00
2018-09-30 00:00:00
2018-10-31 00:00:00
2018-11-30 00:00:00
2018-12-31 00:00:00
2019-01-31 00:00:00
2019-02-28 00:00:00
2019-03-31 00:00:00
2019-04-30 00:00:00
2019-05-31 00:00:00
2019-06-30 00:00:00
2019-07-31 00:00:00
2019-08-31 00:00:00
2019-09-30 00:00:00
2019-10-31 00:00:00
2019-11-30 00:00:00
2019-12-31 00:00:00
2020-01-31 00:00:00
2020-02-29 00:00:00
2020-03-31 00:00:00
2020-04-30 00:00:00
2020-05-31 00:00:00
2020-06-30 00:00:00
2020-07-31 00:00:00
2020-08-31 00:00:00
2020-09-30 00:00:00
2020-10-31 00:00:00
2020-11-30 00:00:00
2020-12-31 00:00:00
2021-01-31 00:00:00
2021-02-28 00:00:00
2021-03-31 00:00:00
2021-04-30 00:00:00
2021-05-31 00:00:00
2021-06-30 00:00:00
2021-07-31 00:00:00
2021-08-31 00:00:00
2021-09-30 00:00:00
2021-10-31 00:00:00
2021-11-30 00:00:00
2021-12-31 00:00:00
2022-01-31 00:00:00
2022-02-28 00:00:00
2022-03-31 00:00:00
2022-04-30 00:00:00
2022-05-31 00:00:00
2022-06-30 00:00:00
2022-07-31 00:00:00
2022-08-31 00:00:00
2022-09-30 00:00:00
2022-10-31 00:00:00
2022-11-30 00:00:00
2022-12-31 00:00:00
2023-01-31 00:00:00
2023-02-28 00:00:00
2023-03-31 00:00:00
2023-04-30 00:00:00
2023-05-31 00:00:00
2023-06-30 00:00:00
2023-07-31 00:00:00
2023-08-31 00:00:00
2023-09-30 00:00:00
2023-10-31 00:00:00
2023-11-30 00:00:00
2023-12-31 00:00:00
2024-01-31 00:00:00
2024-02-29 00:00:00
2024-03-31 00:00:00
2024-04-30 00:00:00
2024-05-31 00:00:00
2024-06-30 00:00:00
2024-07-31 00:00:00
2024-08-31 00:00:00
2024-09-30 00:00:00
2024-10-31 00:00:00
2024-11-30 00:00:00
2024-12-31 00:00:00
2025-01-31 00:00:00
2025-02-28 00:00:00
2025-03-31 00:00:00
2025-04-30 00:00:00
2025-05-31 00:00:00
2025-06-30 00:00:00
2025-07-31 00:00:00
2025-08-31 00:00:00
2025-09-30 00:00:00
2025-10-31 00:00:00
2025-11-30 00:00:00
2025-12-31 00:00:00

In [40]:
data = data.sort_values(by=['id', 'eom'])
data

,id,date,eom,source_crsp,size_grp,obs_main,exch_main,primary_sec,gvkey,iid,...,rvol_252d,zero_trades_252d,corr_1260d,betabab_1260d,rmax5_rvol_21d,age,qmj,qmj_prof,qmj_growth,qmj_safety
0,10026,2024-01-31,2024-01-31,1,small,1,1,1,12825.0,1.0,...,NaN,NaN,NaN,NaN,NaN,469,1.284129,1.204025,-0.067640,1.448983
1,10026,2024-02-29,2024-02-29,1,small,1,1,1,12825.0,1.0,...,NaN,NaN,NaN,NaN,NaN,470,1.282924,1.198607,-0.075588,1.449240
2,10026,2024-03-28,2024-03-31,1,small,1,1,1,12825.0,1.0,...,NaN,NaN,NaN,NaN,NaN,471,1.280630,1.196231,-0.075454,1.447640
3,10026,2024-04-30,2024-04-30,1,small,1,1,1,12825.0,1.0,...,NaN,NaN,NaN,NaN,NaN,472,1.423064,1.291237,0.204842,1.430103
4,10026,2024-05-31,2024-05-31,1,small,1,1,1,12825.0,1.0,...,NaN,NaN,NaN,NaN,NaN,473,1.426046,1.291984,0.203015,1.429422
5,10026,2024-06-28,2024-06-30,1,small,1,1,1,12825.0,1.0,...,0.019756,0.005127,NaN,NaN,0.663480,474,1.424819,1.285306,0.200853,1.424767
6,10026,2024-07-31,2024-07-31,1,small,1,1,1,12825.0,1.0,...,0.018842,0.005171,NaN,NaN,0.774694,475,1.375874,1.290799,0.165077,1.357295
7,10026,2024-08-30,2024-08-31,1,small,1,1,1,12825.0,1.0,...,0.019098,0.005187,NaN,NaN,1.458593,476,1.359689,1.282651,0.150416,1.352312
8,10026,2024-09-30,2024-09-30,1,small,1,1,1,12825.0,1.0,...,0.018334,0.005257,NaN,NaN,0.690187,477,1.361963,1.281207,0.150217,1.353159
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2332902,135685901,2025-12-31,2025-12-31,0,mega,1,1,1,356859.0,1.0,...,NaN,NaN,NaN,NaN,NaN,36,NaN,NaN,NaN,NaN
2332903,136691101,2025-06-30,2025-06-30,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,42,NaN,NaN,NaN,NaN
2332904,136691101,2025-07-31,2025-07-31,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,43,NaN,NaN,NaN,NaN
2332905,136691101,2025-08-29,2025-08-31,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,44,NaN,NaN,NaN,NaN
2332906,136691101,2025-09-30,2025-09-30,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,45,NaN,NaN,NaN,NaN
2332907,136691101,2025-10-31,2025-10-31,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,46,NaN,NaN,NaN,NaN
2332908,136691101,2025-11-28,2025-11-30,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,47,NaN,NaN,NaN,NaN
2332909,136691101,2025-12-31,2025-12-31,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,48,NaN,NaN,NaN,NaN
2332910,136935001,2025-12-31,2025-12-31,0,mega,1,1,1,369350.0,1.0,...,NaN,NaN,NaN,NaN,NaN,36,NaN,NaN,NaN,NaN

In [41]:
# use factors_t to predict return_t+1
data[['id', 'eom', 'ret_exc_lead1m']] # Excess return (ret exc*) in month t+1

                id        eom  ret_exc_lead1m
0            10026 2024-01-31       -0.093089
1            10026 2024-02-29       -0.002675
2            10026 2024-03-31       -0.055155
3            10026 2024-04-30        0.180741
4            10026 2024-05-31       -0.001697
5            10026 2024-06-30        0.034274
6            10026 2024-07-31        0.004413
7            10026 2024-08-31        0.011304
8            10026 2024-09-30       -0.050386
...            ...        ...             ...
2332902  135685901 2025-12-31             NaN
2332903  136691101 2025-06-30             NaN
2332904  136691101 2025-07-31             NaN
2332905  136691101 2025-08-31             NaN
2332906  136691101 2025-09-30             NaN
2332907  136691101 2025-10-31             NaN
2332908  136691101 2025-11-30             NaN
2332909  136691101 2025-12-31             NaN
2332910  136935001 2025-12-31             NaN

[2256068 rows x 3 columns]

In [42]:
save_path = '../data/processed/'

data.to_parquet(save_path + 'data.parquet')

In [43]:
ret = data.pivot_table('ret', index='eom', columns='id')
ret

KeyError: 'ret'

In [ ]:
ret.index.name = 'date'

In [ ]:
new_index = pd.date_range(start_dt, end_dt,freq='ME')
assert ret.index.isin(new_index).all()

In [ ]:
ret.notna().sum(axis=1).plot()

In [ ]:
no_data_dates = ret.notna().sum(axis=1) <= 1000
ret.index[no_data_dates]

In [ ]:
# only have 3 firms
ret.loc['1983-12-31'].notna().sum()

Quality Ratio

In [ ]:
ret.shape
# T=539, N is around 3500 over the entire period...

In [ ]:
save_path = '../data/processed/'

data.to_parquet(save_path + 'data.parquet')

usa csv

In [ ]:
# ret = pd.read_csv('../data/raw/usa.csv')
# ret

In [ ]:
# ret.sort_values(by = ['date', 'id'], inplace=True)
# ret

In [ ]:
# ret['date'] = pd.to_datetime(ret['date'], format='%Y%m%d')
# start_dt = ret['date'].min()
# end_dt = ret['date'].max()
# print ("Date Range: %s --> %s"%(start_dt,end_dt))
# date_unique = sorted(ret['date'].unique())

In [ ]:
# date_unique

In [ ]:
print(data['size_grp'].unique())